---
title: "aggregates historical estimates 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(R2jags)
jags_list <- readRDS(here::here("bmat_m60/jagsdata_m60.rds"))
meta <- readRDS(here::here("bmat_m60/meta_m60.rds"))
samples_cts <- readRDS(here::here("bmat_m60/matdeaths.cts.rds"))
```
Create a dataset of samples from the array
```{r}
# S <- samples_cts %>% dim %>% .[3]
#   samples_df <- tibble::tibble(
#                        c = c(rep(NA, S - meta$C), 1:meta$C),
#                        t = c(rep(NA, S - meta$nyears), 1:meta$nyears),
#                        s = 1:S) %>%
#     tidyr::expand(c, t, s) %>%
#     tidyr::drop_na() %>%
#     dplyr::mutate(mu = as.numeric(NA))
# 
#   for (c in 1:meta$C){
#     for (t in 1:meta$nyears){
#       clog <- samples_df %>% dplyr::pull(c) == c
#       tlog <- samples_df %>% dplyr::pull(t) == t
#       ind <- which(clog & tlog)
#       samples_df[ind, "mu"] <- samples_cts[c,t,]
#     }
#   }
# saveRDS(samples_df, here::here("bmat_m60", "samples_df_m60pro.rds"))
```

Give the draw dataset readable country and year columns
```{r}
samples_df <- readRDS(here::here("bmat_m60", "samples_df_m60pro.rds"))

isos <- meta$iso.c
years <- meta$year.t
iso_df <- data.frame(c = 1:length(isos), iso_alpha_3_code = isos)
years_df <- data.frame(t = 1:length(years), year = years)

samples_df <- samples_df %>% 
  dplyr::left_join(iso_df) %>% 
  dplyr::left_join(years_df)
```

Now to create the weight dataset we need geographic info and birth counts
```{r}
round_name <- "round_testnewsetup3"
geo <- read.csv( 
  here::here("output", round_name, "country_ref.csv")) %>%
  dplyr::mutate(m49_c = as.numeric(m49)) %>%
  dplyr::select(iso_alpha_3_code, m49_c)

# long format for several regions, i.e. isos repeat
geo2 <- readxl::read_excel(here::here("vignettes/internal/aggregate_historic_2019/new_regions_for_request.xlsx"), sheet = 2) %>%
  # dplyr::select(m49_c = m49_c, m49_r) 
  dplyr::select(m49_c = `M49 Code`, m49_r = `M49 Code(region)`)
geo <- geo2 %>% dplyr::left_join(geo, by = "m49_c")
```
Get estimates and bounds for all regions with samples
```{r}
devtools::load_all()
crisis_deaths <- matrix_ct_to_df(matrix = meta$crisisdeaths.ct, C = meta$C, value_name = "crisis_deaths")
deaths <- matrix_ct_to_df(matrix = meta$deaths.ct, C = meta$C, value_name = "deaths")
births <- matrix_ct_to_df(matrix = meta$births.ct, C = meta$C, value_name = "births")
aids <-  matrix_ct_to_df(matrix = jags_list$muaids.ct, C = meta$C, value_name = "aids")
gfr <-  matrix_ct_to_df(matrix = meta$gfr.ct, C = meta$C, value_name = "gfr")
t15t50 <- matrix_ct_to_df(matrix = meta$t15t50.ct, C = meta$C, value_name = "t15t50")
l15 <- matrix_ct_to_df(matrix = meta$l15.ct, C = meta$C, value_name = "l15")

meta_df <- crisis_deaths %>% 
  dplyr::left_join(deaths) %>% 
  dplyr::left_join(births) %>% 
  dplyr::left_join(aids) %>%
  dplyr::left_join(gfr) %>%
  dplyr::left_join(t15t50) %>%
  dplyr::left_join(l15)

samples_df <- samples_df %>%  # this historic object is in form of maternal deaths so we turn make into mmr by dividing by births below
  dplyr::left_join(meta_df) 

quantiles = c(0.1, 0.5, 0.9)
el <- list()
for (region in unique(geo$m49_r)) {
  geo_sub <- geo %>% dplyr::filter(m49_r == region)
  samples_sub <- samples_df %>% dplyr::filter(iso_alpha_3_code %in% geo_sub$iso_alpha_3_code)
  el[[region]] <- samples_sub %>%
    dplyr::mutate(mmr = mu/births) %>%
    dplyr::group_by(year, s) %>%
    dplyr::mutate(weight_denominator = sum(births)) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(weight = births/weight_denominator) %>%
    dplyr::mutate(mmr = mmr * weight) %>%
    dplyr::group_by(year, s) %>%
    dplyr::summarize(mmr = sum(mmr)) %>% # at this point we have samples for region instead of country (or w/e grouping)
    dplyr::ungroup() %>%
    dplyr::group_by(year) %>%
    dplyr::summarise(mmr = quantile(mmr, !!quantiles, na.rm = TRUE)*100000) %>%
    dplyr::mutate(quantiles = !!quantiles) %>%
    dplyr::mutate(m49_r = region) %>%
    dplyr::ungroup()
  
}


estimates <- do.call(rbind, el)

# Reference Area Code (M49) # this is m49_r
# Reference Area Type [for UNSD use only] # this coems from "Reference Area Type [i.e. global, SDG groupings, MDG groupings, etc.]"  
# Reference Area Name # this comes from column named "Region Name" 
# Time Period
# Time Detail [optional] # Calendar year
# Observation Value
# Unit of Measurement # Maternal Mortality per 100,000 live births
# Nature of Data # E
# Disaggregation classification #Uncertainty bounds: lower bound #Uncertainty bounds: mid-point
# Reporting Type # G
# Source # UNMMEIG

regional_info <- readxl::read_excel(here::here("vignettes/internal/aggregate_historic_2019/new_regions_for_request.xlsx"), sheet = 2) %>%
  dplyr::select(`Reference Area Code (M49)` = `M49 Code(region)`,
                `Reference Area Type` = `Reference Area Type [i.e. global, SDG groupings, MDG groupings, etc.]`,
                `Reference Area Name` = `Region Name`) %>%
  dplyr::group_by_all() %>%
  dplyr::summarise()
                
estimates2 <- estimates %>%
  dplyr::rename(`Reference Area Code (M49)` = m49_r,
                `Time Period` = year,
                `Disaggregation classification` = quantiles,
                `Observation Value` = mmr) %>%
  dplyr::mutate(`Time Detail` = "Calendar year",
                `Nature of Data` = "E",
                `Unit of Measurement` = "Maternal Mortality per 100,000 live births",
                `Reporting Type` = "G",
                Source = "UNMMEIG",
                `Disaggregation classification` = ifelse(`Disaggregation classification` == 0.1, "Uncertainty bounds: lower bound",
                                                         ifelse(`Disaggregation classification` == 0.5, "Uncertainty bounds: mid-point",
                                                                "Uncertainty bounds: upper bound"))
                ) %>%
  dplyr::left_join(regional_info)
write.csv(estimates2, row.names = FALSE, "Aggregate_Estimates_Indicator_3.1.1.csv")

```

rbinding on the country data
```{r}
estimates <- read.csv("Aggregate_Estimates_Indicator_3.1.1.csv", check.names=FALSE)
estiamtes_blank <- estimates %>%
  dplyr::filter(`Reference Area Code (M49)` == 1) %>%
  dplyr::mutate(`Observation Value` = NA,
                `Reference Area Code (M49)` = NA)

temp <- readxl::read_excel("blank_template.xlsx", sheet = 1) %>%
  dplyr::select("Reference Area Code (M49)",
                "Reference Area Type" = "Reference Area Type [for UNSD use only]",
                "Reference Area Name")
temp2 <- temp %>%
  dplyr::filter(`Reference Area Type` == "3.0-Country") 




estiamtes_blank_list <- list()
for(code in temp2$`Reference Area Code (M49)`) {
  name <- temp2 %>%
    dplyr::filter(`Reference Area Code (M49)` == code) %>%
    dplyr::pull(`Reference Area Name`) %>%
    unique()
  estiamtes_blank_list[[code]] <- estiamtes_blank %>%
    dplyr::mutate(`Reference Area Code (M49)` = code,
                  `Reference Area Name` = name,
                  `Reference Area Type` = "3.0-Country")
}
estimates_blank_final <- do.call(rbind, estiamtes_blank_list)


estimates_country <- read.csv("mmr_unrounded_m60pry.csv") %>%
  dplyr::select(iso, year, bound, value) %>%
  dplyr::mutate(value = value *100000) %>%
  dplyr::rename(`Disaggregation classification` = "bound",
                #`Reference Area Code (M49)` = "iso",
                `Time Period` = "year",
                `Observation Value` = "value") %>%
  dplyr::mutate(                `Disaggregation classification` = ifelse(`Disaggregation classification` == "lower", "Uncertainty bounds: lower bound",
                                                         ifelse(`Disaggregation classification` == "point", "Uncertainty bounds: mid-point",
                                                                "Uncertainty bounds: upper bound"))) %>%
  dplyr::left_join(geo %>% dplyr::rename(iso = iso_alpha_3_code))%>%
  dplyr::rename(`Reference Area Code (M49)` = "m49_c") %>%
  dplyr::select(-iso)

# checking all isos in my link file
# estimates_country_unedit <- read.csv("mmr_unrounded_m60pry.csv")
# all(estimates_country_unedit$iso %in% geo$iso_alpha_3_code)

estimates_c_final <- estimates_blank_final %>%
  dplyr::select(-`Observation Value`) %>%
  dplyr::left_join(estimates_country, by = c("Disaggregation classification", "Reference Area Code (M49)", "Time Period")) 

final <- rbind(estimates,
      estimates_c_final
      )
write.csv(final, row.names = FALSE, "Aggregate_Estimates_Indicator_3.1.1_version2.csv")
```

