---
title: "aggregates historical estimates 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(R2jags)
jags_list <- readRDS(here::here("test/jagsdata_m60.rds"))
meta <- readRDS(here::here("test/meta_m60.rds"))
samples_cts <- readRDS(here::here("test/matdeaths.cts.rds"))
```

Give the draw dataset readable country and year columns
```{r}
samples_df <- readRDS("samples_df_m60pro.rds")

isos <- meta$iso.c
years <- meta$year.t
iso_df <- data.frame(c = 1:length(isos), iso_alpha_3_code = isos)
years_df <- data.frame(t = 1:length(years), year = years)

samples_df <- samples_df %>% 
  dplyr::left_join(iso_df) %>% 
  dplyr::left_join(years_df)
```

Get aggregate MMR
```{r}
stages <- read.csv("mmr.csv") %>%
  dplyr::filter(bound == "point") %>%
  dplyr::mutate(stage = ifelse(value > 999, 1,
                               ifelse(value < 1000 & value > 299, 2,
                                      ifelse(value < 300 & value > 49, 3,
                                             ifelse(value < 50, 4, NA))))) %>%
  dplyr::filter(year == 2017) %>%
  dplyr::select(iso_alpha_3_code = iso,
                stage)

# Stage 1 MMR >=1000
# Stage 2 MMR 300-999
# Stage 3 MMR 50-299
# Stage 4 MMR <50


devtools::load_all()
crisis_deaths <- matrix_ct_to_df(matrix = meta$crisisdeaths.ct, C = meta$C, value_name = "crisis_deaths")
deaths <- matrix_ct_to_df(matrix = meta$deaths.ct, C = meta$C, value_name = "deaths")
births <- matrix_ct_to_df(matrix = meta$births.ct, C = meta$C, value_name = "births")
aids <-  matrix_ct_to_df(matrix = jags_list$muaids.ct, C = meta$C, value_name = "aids")
gfr <-  matrix_ct_to_df(matrix = meta$gfr.ct, C = meta$C, value_name = "gfr")
t15t50 <- matrix_ct_to_df(matrix = meta$t15t50.ct, C = meta$C, value_name = "t15t50")
l15 <- matrix_ct_to_df(matrix = meta$l15.ct, C = meta$C, value_name = "l15")

meta_df <- crisis_deaths %>% 
  dplyr::left_join(deaths) %>% 
  dplyr::left_join(births) %>% 
  dplyr::left_join(aids) %>%
  dplyr::left_join(gfr) %>%
  dplyr::left_join(t15t50) %>%
  dplyr::left_join(l15)

samples_df <- samples_df %>%  # this historic object is in form of maternal deaths so we turn make into mmr by dividing by births below
  dplyr::left_join(meta_df) 

quantiles = c(0.1, 0.5, 0.9)
el <- list()
for (stage_number in unique(stages$stage)) {
  stage_sub <- stages %>% dplyr::filter(stage == stage_number)
  samples_sub <- samples_df %>% dplyr::filter(iso_alpha_3_code %in% stage_sub$iso_alpha_3_code)
  el[[paste(stage_number)]] <- samples_sub %>%
    dplyr::mutate(mmr = mu/births) %>%
    dplyr::group_by(year, s) %>%
    dplyr::mutate(weight_denominator = sum(births)) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(weight = births/weight_denominator) %>%
    dplyr::mutate(mmr = mmr * weight) %>%
    dplyr::group_by(year, s) %>%
    dplyr::summarize(mmr = sum(mmr)) %>% # at this point we have samples for region instead of country (or w/e grouping)
    dplyr::ungroup() %>%
    dplyr::group_by(year) %>%
    dplyr::summarise(mmr = quantile(mmr, !!quantiles, na.rm = TRUE)*100000) %>%
    dplyr::mutate(quantiles = !!quantiles) %>%
    dplyr::mutate(stage = stage_number) %>%
    dplyr::ungroup()
  
}


estimates_mmr <- do.call(rbind, el)


```

Get aggregates ARR
```{r}


devtools::load_all()
crisis_deaths <- matrix_ct_to_df(matrix = meta$crisisdeaths.ct, C = meta$C, value_name = "crisis_deaths")
deaths <- matrix_ct_to_df(matrix = meta$deaths.ct, C = meta$C, value_name = "deaths")
births <- matrix_ct_to_df(matrix = meta$births.ct, C = meta$C, value_name = "births")
aids <-  matrix_ct_to_df(matrix = jags_list$muaids.ct, C = meta$C, value_name = "aids")
gfr <-  matrix_ct_to_df(matrix = meta$gfr.ct, C = meta$C, value_name = "gfr")
t15t50 <- matrix_ct_to_df(matrix = meta$t15t50.ct, C = meta$C, value_name = "t15t50")
l15 <- matrix_ct_to_df(matrix = meta$l15.ct, C = meta$C, value_name = "l15")

meta_df <- crisis_deaths %>% 
  dplyr::left_join(deaths) %>% 
  dplyr::left_join(births) %>% 
  dplyr::left_join(aids) %>%
  dplyr::left_join(gfr) %>%
  dplyr::left_join(t15t50) %>%
  dplyr::left_join(l15)

samples_df <- samples_df %>%  # this historic object is in form of maternal deaths so we turn make into mmr by dividing by births below
  dplyr::left_join(meta_df) 

quantiles = c(0.1, 0.5, 0.9)
el <- list()
nlag <- 1
quantiles = c(0.1, 0.5, 0.9)
el <- list()
nlag <- 1

period_df <- data.frame(start = c(1999,1990,2000,2010),
                        end = c(2017, 1999, 2009, 2017) )
period_n <- nrow(period_df)
pl <- list()
for (stage_number in unique(stages$stage)) {
  stage_sub <- stages %>% dplyr::filter(stage == stage_number)
  samples_sub <- samples_df %>% 
    dplyr::filter(iso_alpha_3_code %in% stage_sub$iso_alpha_3_code) %>%
    dplyr::mutate(mmr = mu/births) %>%
    dplyr::group_by(year, s) %>%
    dplyr::mutate(weight_denominator = sum(births)) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(weight = births/weight_denominator) %>%
    dplyr::mutate(mmr = mmr * weight) %>%
    dplyr::group_by(year, s) %>%
    dplyr::summarize(mmr = sum(mmr)) %>% # at this point we have samples for region instead of country (or w/e grouping)
    dplyr::ungroup()
  for(n in 1:period_n) {
    start <- period_df$start[n]
    end <- period_df$end[n]
    pl[[n]] <- samples_sub %>%
      dplyr::filter(year %in% c(start, end)) %>%
      dplyr::group_by(s) %>%
      dplyr::mutate(yearlag = year - dplyr::lag(year, n = nlag)) %>%
      dplyr::mutate(mmrlag = dplyr::lag(mmr, n = nlag)) %>%
      dplyr::mutate(arr = -(log(mmr/mmrlag)/yearlag)*100) %>% # using continuous form of reduction
      dplyr::mutate(percent_change_in_mmr = ((mmrlag - mmr)/mmrlag)*100) %>% 
      dplyr::group_by(year) %>%
      tidyr::drop_na() %>%
      dplyr::summarise(arr = quantile(arr, !!quantiles, na.rm = TRUE),
                       percent_change_in_mmr = quantile(percent_change_in_mmr, !!quantiles, na.rm = TRUE)) %>%
      dplyr::mutate(quantiles = !!quantiles) %>%
      dplyr::mutate(period_start = start) %>%
      dplyr::mutate(period_end = end) %>%
      dplyr::mutate(stage = stage_number) %>%
      dplyr::ungroup() %>%
      dplyr::select(-year)
  }
  el[[paste(stage_number)]] <- do.call(rbind, pl)
}

estimates_arr <- do.call(rbind, el)
```
```{r}
write.csv(estimates_mmr, "estimates_per_stage_mmr.csv")
write.csv(estimates_arr, "estimates_per_stage_arr.csv")

```
